### ISSUE TITLE
Extension folder/bookmark display not working as intended for me

### ISSUE THREAD

**Issue by kyyyylehead** [williamsnick606/Better-Bookmarks#16] opened 2019-07-16 00:17 UTC
**Describe the bug**
Upon a fresh installation and reload of the extension, clicking the extension icon shows only the child folders of my bookmark tree. There are no actual bookmarks, none of my folders that have other folders as child nodes, and clicking on the folders that are there does nothing.

**To Reproduce**
1. Pull most recent version of the files from Nick's master branch
2. Clear all extension errors from Chrome's extension page
3. Reload the extension
4. Click the extension icon next to the search bar
5. It will show the wrong folders, and the 'Errors' button from the Extension page shows up again immediately upon clicking the extension icon (presumably when the extension is grabbing info to display).

**Expected behavior**
Upon clicking the extension's icon, there should be my highest-level folders. Upon clicking a folder an accordian-style(?) dropdown shows the contents of the folder, which includes other folders or bookmarks.

**Screenshots**

- Here's a picture of the largest path in my bookmark tree - the only folder in this path that shows up in the extension is 'stratssssss'
![image](https://user-images.githubusercontent.com/52580065/61255529-dc189700-a71d-11e9-8c1c-7905040b0f77.png)

- Here's a picture of the error page for the extension. Basically it's getting angry at each instance of the 'appendChild' function.
![image](https://user-images.githubusercontent.com/52580065/61255683-6eb93600-a71e-11e9-9612-63866b054919.png)

- Here's the result of typing 'git branch -a' (typing just 'git branch' only shows 'master', since that's the only branch I have)
![image](https://user-images.githubusercontent.com/52580065/61256394-8e059280-a721-11e9-86a9-25071cd46651.png)

- Here's the git log of today
[commit_summary.txt](https://github.com/williamsnick606/Better-Bookmarks/files/3394652/commit_summary.txt)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome
 - Version 75.0.3770.100

**Additional context**
@BarryManifold since yours isn't broken maybe it's a problem I created when I synced my fork to the repo this morning? Unless you also tried pulling all of the files from Nick's branch this afternoon and it still worked, then idk.

**Comment by BarryManifold** [comment] 2019-07-16 12:47
@kyyyylehead I need the out put of from this command: ```git log -n 5 js/utils.mjs```.  It looks like you probably ran ```git log``` without providing a filename, which gives information about all files in the current branch, but I only need information about the file giving you the error which your screen shot shows as **js/utils.mjs**.

When I run ```git log -n 3 --pretty=format:%H``` to get the most recent commit my master branch shares with this one, I get the commit hash 616aacb467020fbb8e4b47801f97a3b9764d3f3b.  But like I said, I don't need the commit history from master in general, I just need it for the file causing the error.

I believe that I synced with upstream right after you told me that you were experiencing the error and I haven't been able to reproduce it following your steps or otherwise, so it may be from something you might have changed in master, but I don't know.  Do you always work in branches other than master or do you only work in the master branch?

I did discover a bug related to nested folder structure, which I'm currently in the middle of fixing, but no errors are occurring.  If the error you are experiencing does end up being due to changes you've been working on in master, I strongly recommend that you start using branches from now on, and aside from syncing with upstream, leave master alone.

Perhaps the issue is OS related, but in this case, I really doubt it.  I run Linux with this version of Chromium: **Version 75.0.3770.90 (Official Build) Built on Ubuntu , running on Ubuntu 18.10 (64-bit)**.  But again, I really doubt this is OS related.  As far as differences between Chrome and Chromium go, Chromium is open source and is largely indistinguishable from Chrome and their differences really just arise from Google adding proprietary features to Chrome and things like automatic updates, so their minimal differences are likely not the cause of the error you're experiencing either.

I can't really provide any more insight into the error, nor can I fix an error that I'm not encountering, until I get your output from running ```git log -n 5 js/utils.mjs```.  From your description, the error happens upon clicking the icon, but as you saw in the video I posted on Workplace, that didn't happen to me.  However, the error you're receiving is likely due to certain DOM related functions such as **document.getElementById(...)** not being able to find the correct HTML tags; this can occur in a Chrome extension if you try to access them in files separate from their creation, and sometimes even in functions outside the ones in which the HTML was created.

Dynamically created HTML can be tricky to work with, both in terms of creation and access in a Chrome extension, and it seems like that may be the culprit of your error, but like I said, I need the commit history, i.e., log output, that you have for that specific file before I can move forward with addressing this issue.

**Comment by BarryManifold** [comment] 2019-07-21 03:40
I'm almost certain it was fixed for good in #23.  I introduced a bug when switching from "==" and "!=" to "===" and "!==" that caused the user's bookmarks and folders not to display, but I fixed that in #29.  Therefore, since I'm almost 100% positive I've fixed this bug and it's no longer an issue, I'm going to close this issue.  However, if it so happens that this bug is still lingering around, then whomever encounters it can reopen this issue.

**Closed as completed by BarryManifold** 2019-07-21 03:40 UTC
